import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../component/header/page";
import Footer from "../component/footer/page";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "eclaw",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
          integrity="sha384-nvCwYAPnROuFhV6aP5lv3RD7Ih+CH0S8iMnDfaPQzK1FU9OrA6sOFei2iY7aKGRg"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"
          integrity="sha384-Mh+JOkl/mppz0t1XBwAaHePhLsmBZo6EVH5p9H8R/P2Epbp10dL1/Rnbdp6oaxw5"
          crossOrigin="anonymous"
        /> */}

        <link rel="stylesheet" href="/static/css/bootstrap.min.css" />

        <link rel="stylesheet" href="/static/css/reset.css" />
        <link rel="stylesheet" href="/static/css/gallery_styles.css" />
        <link rel="stylesheet" href="/static/css/main.css" />
        <link rel="stylesheet" href="/static/css/mobile.css" />
        <link rel="stylesheet" href="/static/css/styles.css" />
        <link rel="stylesheet" href="/static/owl-carousel/animate.css" />
        <link rel="stylesheet" href="/static/owl-carousel/owl.carousel.css" />
        <link rel="stylesheet" href="/static/owl-carousel/owl.theme.css" />
        <link
          rel="stylesheet"
          href="/static/owl-carousel/owl.transitions.css"
        />
        <link rel="stylesheet" href="/static/owl-carousel/owl-ken-burns.css" />
        <link
          rel="stylesheet"
          href="/static/font-awesome-4.3.0/css/font-awesome.css"
        />
        <link rel="stylesheet" href="/static/gerege/gerege-codes.css" />
        <link rel="stylesheet" href="/static/gerege/gerege-embedded.css" />
        <link rel="stylesheet" href="/static/gerege/gerege-ie7-codes.css" />
        <link rel="stylesheet" href="/static/gerege/gerege-ie7.css" />
        <link rel="stylesheet" href="/static/gerege/gerege.css" />
        <link rel="stylesheet" href="/static/swiper/swiper.min.css" />
      </head>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />

        {/* <script
          src="https://code.jquery.com/jquery-3.6.0.min.js"
          integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5/8Bp5x1yog60v8/J58XaIrIxF9/qlv5A5mf7U8N"
          crossOrigin="anonymous"
        /> */}

        <script src="https://code.jquery.com/jquery-3.5.1.min.js" />
        <script src="https://code.jquery.com/jquery-1.9.3.min.js" />

        <script src="static/js/bootstrap.min.js" async />
        <script src="static/owl-carousel/owl.carousel.js" async />
        <script src="static/js/jquery.matchHeight-min.js" async />
        <script src="static/js/scripts.js" async />
        <script src="static/js/custom.js" async />
        {/* <script src="static/swiper/swiper.min.js" /> */}
      </body>
    </html>
  );
}
