import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../component/header/page";
import Footer from "../component/footer/page";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "eclaw",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/static/css/bootstrap.min.css" />

        <link rel="stylesheet" href="/static/css/reset.css" />
        <link rel="stylesheet" href="/static/css/gallery_styles.css" />
        <link rel="stylesheet" href="/static/css/main.css" />
        <link rel="stylesheet" href="/static/css/mobile.css" />
        <link rel="stylesheet" href="/static/css/styles.css" />
        <link rel="stylesheet" href="/static/owl-carousel/animate.css" />
        <link rel="stylesheet" href="/static/owl-carousel/owl.carousel.css" />
        <link rel="stylesheet" href="/static/owl-carousel/owl.theme.css" />
        <link
          rel="stylesheet"
          href="/static/owl-carousel/owl.transitions.css"
        />
        <link rel="stylesheet" href="/static/owl-carousel/owl-ken-burns.css" />
        <link
          rel="stylesheet"
          href="/static/font-awesome-4.3.0/css/font-awesome.css"
        />
        <link rel="stylesheet" href="/static/gerege/gerege-codes.css" />
        <link rel="stylesheet" href="/static/gerege/gerege-embedded.css" />
        <link rel="stylesheet" href="/static/gerege/gerege-ie7-codes.css" />
        <link rel="stylesheet" href="/static/gerege/gerege-ie7.css" />
        <link rel="stylesheet" href="/static/gerege/gerege.css" />
        <link rel="stylesheet" href="/static/swiper/swiper.min.css" />
      </head>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />

        <script src="static/js/bootstrap.min.js" async />
        <script src="static/owl-carousel/owl.carousel.js" async />
        <script src="static/js/jquery.matchHeight-min.js" async />
        <script src="static/js/scripts.js" async />
        <script src="static/js/custom.js" async />
        <script src="static/swiper/swiper.min.js" async />
      </body>
    </html>
  );
}
